// Auto-generated by scripts/prep-images.mjs
// Maps marketcap tier (0-99) to the UUID-named image file.
// Each tier represents $10K of marketcap; tier 99 = $990K+.
//
// PLACEHOLDER: this file is committed as a stub. After running
//   node scripts/prep-images.mjs <your-image-dir>
// it will be replaced with the real UUID mapping.

export const TIER_COUNT = 100;

/**
 * Tier-to-UUID mapping. TIER_IMAGES[tier] = image UUID (without .webp).
 * Tier 0 is the sparsest scene (lowest marketcap).
 * Tier 99 is the most populated scene (highest marketcap).
 */
export const TIER_IMAGES: readonly string[] = [
  "PLACEHOLDER_RUN_PREP_SCRIPT",
];

/**
 * Get the public URL for a tier image on the deployed domain.
 * @param tier 0 to TIER_COUNT-1
 * @param domain e.g. "https://b20society.com"
 */
export function tierImageUrl(tier: number, domain: string): string {
  if (tier < 0 || tier >= TIER_COUNT) {
    throw new Error(`Invalid tier ${tier}, must be 0-${TIER_COUNT - 1}`);
  }
  return `${domain}/images/${TIER_IMAGES[tier]}.webp`;
}
