#!/usr/bin/env node
/**
 * Image preparation script for B20 Society.
 *
 * Takes 100 token tier images (any name, any order) and:
 *   1. Generates 100 random UUIDs
 *   2. Renames copies to UUID format
 *   3. Generates lib/tier-images.ts with the tier-to-UUID mapping
 *
 * Usage:
 *   node scripts/prep-images.mjs <input-dir> [--dry-run]
 *
 * Args:
 *   <input-dir>  Directory containing the 100 token images (any format)
 *   --dry-run    Print actions without writing files
 *
 * Output:
 *   - public/images/{uuid}.webp  (100 renamed copies)
 *   - lib/tier-images.ts          (TypeScript constant array)
 *
 * Requires: 100 image files in the input directory.
 *           Files can be any name; they'll be sorted alphabetically
 *           and assigned to tiers 0-99 in that order.
 *
 *           Tier 0 = $0 marketcap (sparsest scene)
 *           Tier 99 = $990K+ (most populated)
 */

import { randomUUID } from "node:crypto";
import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = path.resolve(__dirname, "..");

const TIER_COUNT = 100;
const IMAGE_EXT = ".webp";
const PUBLIC_IMAGES_DIR = path.join(PROJECT_ROOT, "public", "images");
const NFT_IMAGES_DIR = path.join(PUBLIC_IMAGES_DIR, "nft");
const TIER_MAPPING_FILE = path.join(PROJECT_ROOT, "lib", "tier-images.ts");

function parseArgs() {
  const args = process.argv.slice(2);
  const opts = { inputDir: null, dryRun: false };
  for (const arg of args) {
    if (arg === "--dry-run") {
      opts.dryRun = true;
    } else if (!opts.inputDir) {
      opts.inputDir = arg;
    }
  }
  return opts;
}

function isImageFile(name) {
  const ext = path.extname(name).toLowerCase();
  return [".webp", ".png", ".jpg", ".jpeg", ".gif"].includes(ext);
}

function escapeForTS(s) {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

async function main() {
  const opts = parseArgs();

  if (!opts.inputDir) {
    console.error("Usage: node scripts/prep-images.mjs <input-dir> [--dry-run]");
    console.error("Example: node scripts/prep-images.mjs ./raw-images");
    process.exit(1);
  }

  const inputDir = path.resolve(opts.inputDir);
  console.log(`Input directory: ${inputDir}`);
  console.log(`Dry run: ${opts.dryRun ? "YES" : "no"}`);

  // List image files
  let entries;
  try {
    entries = await fs.readdir(inputDir);
  } catch (err) {
    console.error(`Cannot read input dir: ${err.message}`);
    process.exit(1);
  }
  const imageFiles = entries.filter(isImageFile).sort();

  if (imageFiles.length !== TIER_COUNT) {
    console.error(
      `Expected ${TIER_COUNT} images, found ${imageFiles.length}`,
    );
    console.error(
      `If you have a different number, edit TIER_COUNT in this script.`,
    );
    process.exit(1);
  }
  console.log(`Found ${imageFiles.length} image files (sorted).`);

  // Generate UUIDs (deterministic seed for reproducibility if needed)
  const uuids = Array.from({ length: TIER_COUNT }, () => randomUUID());

  // Check for collisions
  const unique = new Set(uuids);
  if (unique.size !== TIER_COUNT) {
    console.error("UUID collision! Run again.");
    process.exit(1);
  }

  // Print plan
  console.log("\n=== Plan ===");
  for (let tier = 0; tier < TIER_COUNT; tier++) {
    const src = path.join(inputDir, imageFiles[tier]);
    const dst = path.join(PUBLIC_IMAGES_DIR, `${uuids[tier]}${IMAGE_EXT}`);
    if (tier < 3 || tier === TIER_COUNT - 1) {
      console.log(`  tier ${tier}: ${imageFiles[tier]} -> ${uuids[tier]}${IMAGE_EXT}`);
    } else if (tier === 3) {
      console.log(`  ... (${TIER_COUNT - 4} more) ...`);
    }
  }

  if (opts.dryRun) {
    console.log("\n[dry-run] no files written.");
    return;
  }

  // Ensure output dirs exist
  await fs.mkdir(PUBLIC_IMAGES_DIR, { recursive: true });
  await fs.mkdir(NFT_IMAGES_DIR, { recursive: true });

  // Copy files
  console.log("\nCopying files...");
  for (let tier = 0; tier < TIER_COUNT; tier++) {
    const src = path.join(inputDir, imageFiles[tier]);
    const dst = path.join(PUBLIC_IMAGES_DIR, `${uuids[tier]}${IMAGE_EXT}`);
    await fs.copyFile(src, dst);
  }
  console.log(`Copied ${TIER_COUNT} files to ${PUBLIC_IMAGES_DIR}`);

  // Generate tier-images.ts
  const tsLines = [
    "// Auto-generated by scripts/prep-images.mjs",
    "// Maps marketcap tier (0-99) to the UUID-named image file.",
    "// Each tier represents $10K of marketcap; tier 99 = $990K+.",
    "",
    `export const TIER_COUNT = ${TIER_COUNT};`,
    "",
    "/**",
    " * Tier-to-UUID mapping. TIER_IMAGES[tier] = image UUID (without .webp).",
    " * Tier 0 is the sparsest scene (lowest marketcap).",
    ` * Tier ${TIER_COUNT - 1} is the most populated scene (highest marketcap).`,
    " */",
    "export const TIER_IMAGES: readonly string[] = [",
    ...uuids.map((u, i) => `  "${escapeForTS(u)}", // tier ${i}`),
    "];",
    "",
    "/**",
    " * Get the public URL for a tier image on the deployed domain.",
    " * @param tier 0 to TIER_COUNT-1",
    ` * @param domain e.g. "https://b20society.com"`,
    " */",
    "export function tierImageUrl(tier: number, domain: string): string {",
    "  if (tier < 0 || tier >= TIER_COUNT) {",
    "    throw new Error(`Invalid tier ${tier}, must be 0-${TIER_COUNT - 1}`);",
    "  }",
    `  return \`\${domain}/images/\${TIER_IMAGES[tier]}${IMAGE_EXT}\`;`,
    "}",
    "",
  ];
  await fs.writeFile(TIER_MAPPING_FILE, tsLines.join("\n"));
  console.log(`Wrote ${TIER_MAPPING_FILE}`);

  // Print commit-ready summary
  console.log("\n=== Done ===");
  console.log(`Next steps:`);
  console.log(`  1. Verify images in public/images/`);
  console.log(`  2. git add public/images/ lib/tier-images.ts`);
  console.log(`  3. git commit -m "Add 100 token tier images with UUID mapping"`);
  console.log(`  4. git push origin main  (Vercel auto-deploys)`);
}

main().catch((err) => {
  console.error("Error:", err);
  process.exit(1);
});
